apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  labels:
    name: mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongo
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo
  labels:
    app: mongo

spec:
  selector:
    matchLabels:
      app: mongo
  replicas: 3
  serviceName: mongo-service
  template:
    metadata:
      labels:
        role: mongo
        environment: test
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:latest
          command:
            - mongod
            - "--bind_ip"
            - 0.0.0.0
            - "--replSet"
            - rs0
            - "--smallfiles"
            - "--noprealloc"
            
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db

        - name: mongo-config
          image: cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
            - name: KUBERNETES_SERVICE_NAME
              value: mongo-service
  volumeClaimTemplates:
    - metadata:
        name: mongo-persistent-storage
      spec:
        storageClassName: faster
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi