
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: web-app

spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app

  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: test-repo
          image: sareenv/test-repo:1
          resources:
            limits: 
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 8080
          env:

            - name: username
              valueFrom:
                secretKeyRef:
                  key: mongo-root-username
                  name: mongo-secret

            - name: password
              valueFrom:
                secretKeyRef:
                  key: mongo-root-password
                  name: mongo-secret

            - name: dbUrl
              value: mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo
---

apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001