
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 annotations:
  name: app-deployment
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: app-deployment
  minReplicas: 3
  maxReplicas: 6
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: Utilization
        averageUtilization: 30